package com.k1llm3sixy.colorcodehelper.enum

enum class Colors(val color: String, val colorCode: String) {
    BLACK("&0 - §0Black", "&0"),
    DARK_BLUE("&1 - §1Dark Blue", "&1"),
    DARK_GREEN("&2 - §2Dark Green", "&2"),
    DARK_AQUA("&3 - §3Dark Aqua", "&3"),
    DARK_RED("&4 - §4Dark Red", "&4"),
    DARK_PURPLE("&5 - §5Dark Purple", "&5"),
    GOLD("&6 - §6Gold", "&6"),
    GRAY("&7 - §7Gray", "&7"),
    DARK_GRAY("&8 - §8Dark Gray", "&8"),
    BLUE("&9 - §9Blue", "&9"),
    GREEN("&a - §aGreen", "&a"),
    AQUA("&b - §bAqua", "&b"),
    RED("&c - §cRed", "&c"),
    LIGHT_PURPLE("&d - §dLight Purple", "&d"),
    YELLOW("&e - §eYellow", "&e"),
    WHITE("&f - §fWhite", "&f"),
    BOLD("&l - §lBold", "&l"),
    UNDERLINE("&n - §nUnderline", "&n"),
    ITALIC("&o - §oItalic", "&o"),
    STRIKETHROUGH("&m - §mStrikethrough", "&m"),
    MAGIC("&k - §kMagic", "&k"),
    RESET("&r - §rReset", "&r"),
}